<?php

//INITIALLY, I CREATED AN ABSTRACT CLASS NAMED ANIMAL WITH AN ABSTRACT METHOD CALLED MAKESOUND. 
//HOWEVER, I REALIZED THAT I DIDN’T NEED AN ENTIRE CLASS. I JUST NEEDED A METHOD FOR THE DOG AND CAT CLASSES 
//TO MAKE THEIR RESPECTIVE SOUNDS. THIS CAN BE ACHIEVED USING AN INTERFACE.

interface sound{
    public function makeSound(): string;
}